Repository abhishekpatelmc/sustainhack, pull requests merged in 2022-12, with the labels that each got.

#1 feat: #002 Navbar Added -- Basic Homepage
  components/Navbar.tsx
  src/pages/index.tsx
Labels: enhancement

#5 feat: #005 Navbar working fine -- moved to src directory
  src/components/Navbar.tsx
  src/pages/index.tsx
Labels: bug

#6 feat: #006 firebase-storage and create-post setup
  src/pages/create-post.tsx
  src/server/lib/firebase.ts
Labels: enhancement

#7 feat: #007 Started designing create post page
  src/components/Modal.tsx
  src/pages/create-post.tsx
Labels: enhancement

#11 feat: #11 all posts displaying -- images domain added
  next.config.js
  src/components/Navbar.tsx
  src/pages/create-post.tsx
  src/pages/index.tsx
Labels: bug, enhancement, help wanted

#12 feat: #012 Login Page working -- Able to create post when logged in
  src/components/Navbar.tsx
  src/pages/index.tsx
Labels: enhancement, help wanted

#13 feat: #013 Active - Inactive Toggle Set -- Post Component Created
  src/components/Post.tsx
  src/pages/[id].tsx
  src/pages/index.tsx
Labels: enhancement, help wanted

#14 feat: #014 Add post added for Navbar
  src/components/Navbar.tsx
Labels: enhancement

#15 feat: #016 - Post card designed
  src/components/Navbar.tsx
  src/components/Post.tsx
  src/pages/create-post.tsx
  src/pages/index.tsx
Labels: enhancement

#16 feat: #017 File Upload Designed - Post Image Fixed
  src/components/Modal.tsx
  src/components/Post.tsx
  src/pages/create-post.tsx
Labels: bug, enhancement, help wanted

#17 feat: #018 Created Posts Page - Home Page
  src/components/Navbar.tsx
  src/components/Post.tsx
  src/pages/index.tsx
  src/pages/posts.tsx
Labels: bug, enhancement

#19 feat: #020
  src/pages/[id].tsx
  src/pages/id.tsx
  src/pages/index.tsx
Labels: enhancement

#22 feat: #021 Home page designed
  src/pages/[id].tsx
  src/pages/index.tsx
Labels: enhancement
